export const REQUEST_USERS_DATA = 'REQUEST_USERS_DATA';
export const RECEIVE_USERS_DATA = 'RECEIVE_USERS_DATA';
export const REQUEST_COUNTRY_DATA = 'REQUEST_COUNTRY_DATA';
export const REQUEST_PRODUCT_DATA = 'REQUEST_PRODUCT_DATA';


